### ISSUE TITLE
frame masks and other nodes

### ISSUE THREAD

**Issue by mrpurest** [hypothetical-inc/GafferDeadline#11]
hello,
The "frame mask" node is a task node, but it is not really designed to be executed in the way other nodes might be (eg a render). 
prehaps your dispatcher needs the option to skip nodes?

**Comment by ericmehl** [comment]
I agree that there could be some better logic to skipping some nodes to make the overall render tree execute faster. FrameMask can't be skipped in _all_ cases because if there is a PostTask connected to it that dependency needs to be represented in Deadline.

I'm thinking a combination of skipping some nodes (if they don't have post tasks, etc.) and a flag attached to Deadline jobs to signal the job is only for dependencies and does not need to actually execute.

That would allow things like FrameMask and TaskList nodes to not have to load the script and just mark the job as successful.

Are you seeing big slowdowns as a result of loading and executing these non-action tasks? Or cluttering up your Deadline monitor? I'm curious about your use case to see if the above would be a good solution or not.

**Comment by mrpurest** [comment]
Cluttering deadline is not great for sure - and deadline is not very good with dependencies - they take a long time to resolve and historically they are unreliable (with dependent jobs sometimes not ever being released).  for what I am currently sending to the farm, more time is spent waiting for the dependencies to resolve than anything actual rendering etc.

Also, there seems to be some bugs around some of these nodes:

 Traceback (most recent call last):
  File "/mnt/pipeline/ATK_PIPELINE/third_party/gaffer/GafferDeadline/v0.50.0.1/python/GafferDeadline/DeadlineDispatcher.py", line 116, in _doDispatch
    self.__buildDeadlineDependencyWalk(root_job)
  File "/mnt/pipeline/ATK_PIPELINE/third_party/gaffer/GafferDeadline/v0.50.0.1/python/GafferDeadline/DeadlineDispatcher.py", line 148, in __buildDeadlineDependencyWalk
    job.buildTaskDependencies()
  File "/mnt/pipeline/ATK_PIPELINE/third_party/gaffer/GafferDeadline/v0.50.0.1/python/GafferDeadline/GafferDeadlineJob.py", line 183, in buildTaskDependencies
    task.setFrameRange(dep.getStartFrame(), dep.getEndFrame())
  File "/mnt/pipeline/ATK_PIPELINE/third_party/gaffer/GafferDeadline/v0.50.0.1/python/GafferDeadline/GafferDeadlineTask.py", line 75, in setFrameRange
    if int(start_frame) != start_frame or int(end_frame) != end_frame:
TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by ericmehl** [comment]
Yeah, I've found Deadline's dependencies to be frustrating at times too. Is there potentially a different way to structure your Gaffer script to make for less dependencies? I've found there are quite a few ways to structure my graphs and some are much more efficient than others.

**Comment by ericmehl** [comment]
Can you give me an example of the graph that is triggering that error? It's been tricky rooting out all the conversions from Gaffer batches to Deadline tasks so it looks like you found an edge case that I've missed.

**Comment by mrpurest** [comment]
yes, simple example is to create a pythonCommand attached to a tasklist. (not sure if my image upload will work) 

![image](https://user-images.githubusercontent.com/10486058/81286302-ba93ed80-9058-11ea-913b-c902dcc84f4f.png)

I mostly have work arounds for these issues - like you suggest - but it would give more flexibility if they were sorted out.

**Comment by mrpurest** [comment]
fyi: I am very thankful of you making this code available. 
Basically has made it possible to use gaffer on a project that otherwise I wouldn't be able to.
R

**Comment by ericmehl** [comment]
Hey @mrpurest, apologies for taking so long to get back to this. I'm looking at the dispatch error in more detail now and I'm finding that I can only trigger the error in your graph setup above if I have the PythonCommand node with no code. Is that the case for you too?

Are there other graph setups that trigger the same error?

I think the problem in the case of no code in a PythonCommand is that Gaffer is smart enough to not generate a batch for it if there is no code. But my Deadline submitter still tries to create a dependency for the TaskList which triggers the error.

In this example the best thing to do would be to skip the TaskList as well since its upstream node doesn't do anything. But I want to make sure there aren't other known cases where doing that would be the wrong solution.

**Comment by mrpurest** [comment]
Hi,

I am pretty sure this is not the only case there there are issues - since I was trying to do real things! - I just tried to give the most simple example I could.
We have worked around the issue - but I will remind myself and get back to you.

R

**Comment by ericmehl** [comment]
Sounds good - if you have time to find what was causing it again I can take a look. I was only able to recreate the problem in that trivial case but would like to catch others too.

**Comment by Kaiz3rTool** [comment]
hi, I have the same issue in this production case
![image](https://user-images.githubusercontent.com/4272733/120093587-a3201a80-c11b-11eb-93bc-ca4065f6dd51.png)
the problem is from the "SQ00X_Shotlist" wedge node that seems undispatchable to gafferdeadline, as if I dispatch framelist only it works
a local dispatch with gaffer one also works as expected so I guess gafferdeadline is the issue here

**Comment by ericmehl** [comment]
I'll try recreating that setup and see if I can reproduce it and should be able to get to the bottom of this bug.

Are there any possible scenarios where the SQ002_FrameMask node would generate 0 tasks / batches? It looks like an expression is driving it, is that correct? For example if you submit all of the shots 001-005 to Deadline from the SQ002_FrameMask node, do all of them create an actual job with frames to render?

**Comment by Kaiz3rTool** [comment]
hi Eric,
I don't think it's possible to return 0 tasks from frameMask, as it follows the selected shot from wedge node

the frameRange is driven by a spreadsheet that change the mask according to the shot selection, like this 
![image](https://user-images.githubusercontent.com/4272733/120335343-aff66700-c2f1-11eb-897f-075f62c1f472.png)

so the wedge can't send a shot that the frameMask doesn't handle as it have the exact same list of shots

I can submit anything from the framemask to deadline, but submitting the wedge with different shots result the same errors than @mrpurest

**Comment by ericmehl** [comment]
Ok, I'll see if I can reproduce that.

**Comment by ericmehl** [comment]
Hey @Kaiz3rTool, I just released[ 0.55.0.0](https://github.com/hypothetical-inc/GafferDeadline/releases/tag/0.55.0.0) which should fix your error with Wedge nodes.

Even better, it does not submit the FrameMask and Wedge nodes at all now, instead passing through dependencies (if any). That should make processing the full submission in Deadline quite a bit faster since releasing tasks and general Gaffer startup times can get slow.

Give it a try and see how that works for you.

**Comment by Kaiz3rTool** [comment]
Hello @ericmehl 
thanks for the new version !
for me, it doesn't work as it don't dispatch imagewriters node so i can't test it in production environment
here is a simple scene where dispatching the 'imagewriter" send "arnoldrender" node to deadline but not the image writer itself
[multichannelExr.gfr.zip](https://github.com/hypothetical-inc/GafferDeadline/files/6759447/multichannelExr.gfr.zip)

in a more complex branching the dispatch fail with this message
![deadlinedispatch](https://user-images.githubusercontent.com/4272733/124374942-88533f80-dc9f-11eb-8bc6-a2b6c6199fc7.png)
 
bests

**Comment by ericmehl** [comment]
Thanks for bringing that up @Kaiz3rTool! It is indeed a bug in GafferDeadline where some values couldn't be hashed, in this case `FrameData`.

I have a fix up at https://github.com/ericmehl/GafferDeadline/tree/fix_task_hashing. Can you download the code for that branch and verify it fixes the problem for you? Installation is the same as a regular release. Or if it's easier, you want you can just overwrite "python/GafferDeadline/GafferDeadlineTask.py" to your installation. That is the only file that changed.

If that works, I'll make a new release including that fix.

**Comment by Kaiz3rTool** [comment]
hey Eric, thanks for the patch, that works as expected to me, thanks !
i have an other bug but i will open a need ticket for this in a minut

**Comment by ericmehl** [comment]
Wonderful! I just put out a new release that includes that fix : https://github.com/hypothetical-inc/GafferDeadline/releases/tag/0.55.2.0

**Comment by Kaiz3rTool** [comment]
works like a charm, thanks
i can't close the ticket but to me it's all fine
