### ISSUE TITLE
error on dispatch, random task order

### ISSUE THREAD

**Issue by Kaiz3rTool** [hypothetical-inc/GafferDeadline#13]
Hello Eric, 
Just tried version 51 of  gafferDeadline and now I have errors on dispatch with gaffer 0.57.5 and 0.58 (both worked well with previous versions of GafferDeadline)

some tasks are dispatched then it stop and rise an error : 
`ERROR : Dispatch Error 
Traceback (most recent call last):
  File "/mnt/Pipeline/Gaffer/deadline/python/GafferDeadline/DeadlineDispatcher.py", line 121, in _doDispatch
    self.__submitDeadlineJob(root_job, dispatch_data)
  File "/mnt/Pipeline/Gaffer/deadline/python/GafferDeadline/DeadlineDispatcher.py", line 346, in __submitDeadlineJob
    job_id, output = deadline_job.submitJob(job_file_path=job_file_path, plugin_file_path=plugin_file_path)
  File "/mnt/Pipeline/Gaffer/deadline/python/GafferDeadline/GafferDeadlineJob.py", line 239, in submitJob
    raise(RuntimeError, "Deadline submission failed: \n{}".format(result[1]))
RuntimeError
`

also submitted tasks are in random orders, It doesn't follow pretasks order. sometime pretasks.0 is submitted after pretask.1 It can be interesting to create dependency for preserve prestasks.X order

let me know if you need more infos
bests

**Comment by Kaiz3rTool** [comment]
also, postTasks are not a dependency of pretasks, could be great to have it too to not let deadline failed the job

bests

**Comment by Kaiz3rTool** [comment]
forget me, for any reasons it's working fine now
