### ISSUE TITLE
[WIN] Deadline 10.3.1.3 - Gaffer 1.3.12.0 render executable could not be found

### ISSUE THREAD

**Issue by vNicolini** [hypothetical-inc/GafferDeadline#65]
I've setup the GafferDeadline components, i can submit something (although expectedly it's not working on 1.4.0.0b1) but then the task fails because it supposedly can't find the executable.

I've tried pointing deadline's plugin executable dir to the following:
- my gaffer.bat wrapper
- my wrapper.bat renamed with Gaffer's version
- gaffer's vanilla wrapper

It's always throwing the same error:
```
=======================================================
Error
=======================================================
Error: Gaffer 1.3.12.0 render executable could not be found in the semicolon separated list "%HOME%/gaffer_1_3_12_0_0_0~/gaffer_1_3_12_0_0_0;G:\pipeline\Utilities\DCC_Wrapper\Gaffer\1.4\gaffer.bat;G:\pipeline\Utilities\DCC_Wrapper\Gaffer\1.4\gaffer_1.3.12.0.bat;G:\pipeline\DCCs\gaffer-1.3.12.0-windows\gaffer.cmd". The path to the render executable can be configured from the Plugin Configuration in the Deadline Monitor.
   at Deadline.Plugins.PluginWrapper.RenderTasks(Task task, String& outMessage, AbortLevel& abortLevel)

=======================================================
Type
=======================================================
RenderPluginException

=======================================================
Stack Trace
=======================================================
   at Deadline.Plugins.SandboxedPlugin.d(DeadlineMessage bgu, CancellationToken bgv)
   at Deadline.Plugins.SandboxedPlugin.RenderTask(Task task, CancellationToken cancellationToken)
   at Deadline.Slaves.SlaveRenderThread.c(TaskLogWriter ajz, CancellationToken aka)
```

I'm using:
- Gaffer 1.3.12.0 - windows
- Deadline 10.3.1.3 - windows

Please let me know if you need more info.

Cheers,
VNI

**Comment by ericmehl** [comment]
I think your plugin executable path might be slightly incorrect. Unless you've moved the `gaffer.cmd` file from where it is in the install package, it should be in a `bin` directory, so `G:\pipeline\DCCs\gaffer-1.3.12.0-windows\bin\gaffer.cmd` in your case. And in the case of your first entry, it looks like a rogue `~` may have snuck in?

**Comment by vNicolini** [comment]
Hey Eric, 
thanks for the flag regarding the `gaffer.cmd` path, with it now starts the render, then expectedly fails because missing envVars (ie: `ARNOLD_ROOT`, etc ...). I had to fix my custom wrapper (adding `*%` to it which i'm sure i had at some point!) for it to be picked up too. 

Apologies for the false alarm
